ADVENTURE_HOOK = [
    "Free (roll on Encounters-Intelligent or Animals)",
    "Slay (roll on Encounters)",
    "Capture (roll on Encounters or Animals)",
    "Safely transport (d4, roll on 1 Encounters 2 Animals 3-4 Objects)",
    "Locate (d6, roll on 1-Encounters 2-Instant Interior Rooms 3-Instant Forest Landmarks 4-Instant Garden Landmarks 5 Animals 6 Objects)",
    "Acquire (roll on Objects or Animals)",
    "Destroy (roll on Objects)",
    "Seduce (roll on Encounters-Intelligent)",
    "Frame (roll on Encounters-Intelligent or Animals) for a crime",
    "Spy on (roll on Encounters-Intelligent)",
    "Re-roll, action must be performed during (roll Event)",
    "Map (d20 1-Castle Cachtice 2-Castle Poenari 3-8 Garden 9-14 Forest 15-20 Interior.)",
    "Investigate Murder of (roll on Encounters- Intelligent)",
    "Investigate Theft of (roll on Objects) belonging to (Encounters-Intelligent)",
    "Prevent (roll on Event)",
    "Ruin (Event)",
    "Secretly sell (roll on Objects) to (roll on Encounters-Intelligent)",
    "Recruit (roll on Encounters-Intelligent)",
    "Defend (roll on Location)",
    "Impersonate (roll on Encounters- Intelligent) during (roll on Event)"
]

ANIMAL = [
    "Mouse",
    "Bat",
    "Frog",
    "Loach",
    "Tortoise",
    "Crow",
    "Magpie",
    "Lorry",
    "Maggot",
    "Duck",
    "Badger",
    "Mongoose",
    "Lizard",
    "Frilled lizard",
    "Salamander",
    "Tamarin",
    "Spider",
    "Squirrel",
    "Mole",
    "Scorpion",
    "Eel",
    "Snake",
    "Armadillo",
    "Lemur",
    "Otter",
    "Rat",
    "Cat",
    "Fox",
    "Sloth",
    "Swan",
    "Hedgehog",
    "Chameleon",
    "Ferret",
    "Centipede",
    "Mantis",
    "Firefly ",
    "Weasel ",
    "Lobster ",
    "Duck ",
    "Hedgehog ",
    "Rabbit ",
    "Hare ",
    "Shrike ",
    "Beetle ",
    "Goldfish ",
    "Crab",
    "Leech",
    "Butterfly/Moth",
    "Amoeba",
    "Bream",
    "Ray",
    "Lamprey",
    "Wolf",
    "Stag",
    "Hog",
    "Vulture",
    "Tiger ",
    "Lion",
    "Leopard ",
    "Panther ",
    "Ocelot ",
    "Boar",
    "Cheetah",
    "Crane",
    "Alligator/Crocodile ",
    "Dog",
    "Elephant",
    "Jackal",
    "Goat",
    "Octopus",
    "Horse",
    "Hyena",
    "Jaguar",
    "Warthog",
    "Owl",
    "Panda",
    "Rhinoceros",
    "Zebra",
    "Whale",
    "Wolverine",
    "Bear",
    "Shark",
    "Gorilla",
    "Peacock",
    "Hammerhead shark",
    "Lynx",
    "Boa Constrictor",
    "Yak",
    "Giraffe or T-Rex",
    "Hippo or Pterodactyl",
    "Kangaroo or Brontosaurus",
    "Ostrich or Sabretoothed Tiger",
    "Penguin or Mastodon",
    "Swordfish",
    "Coelacanth",
    "Granjoro Jellyfish (10’ diameter, look it up)",
    "Pangolin",
    "Komodo Dragon",
    "Squid",
    "Chimpanzee/Orangutan"
]

ENCOUNTER = [
    "Bat/Undead bird Swarm",
    "Little Crocodile",
    "Ozwick",
    "Sleeper",
    "Ordinary Human",
    "Goblins, Hobgoblins, etc.",
    "Footmen in Livery",
    "Cheshire Cat",
    "Mome Rath",
    "Wild Boar",
    "Wolf or Tiger",
    "The Rabbit",
    "March Hare",
    "Tove",
    "Pseudoturtle",
    "Colorless Pawn",
    "Pale Pawn",
    "Red Pawn",
    "Rose Nageire",
    "Tiger Lily Nageire",
    "Violet Nageire",
    "Order of Spades",
    "Order of Hearts",
    "Order of Diamonds",
    "Order of Clubs",
    "Jub",
    "Pudding",
    "Unicorn",
    "Witch (any old witch)",
    "Colorless Knight",
    "Pale Knight",
    "Red Knight",
    "Great Grey Grub",
    "Colorless Bishop",
    "Pale Bishop",
    "Red Bishop",
    "Duchess",
    "Knave of Hearts",
    "Hatter",
    "Pale Rook",
    "Colorless Rook",
    "Red Rook",
    "Sphinx",
    "Red Bride (Ilona)",
    "Red Bride (Tizala)",
    "Red Bride (Ildana)",
    "King of Hearts",
    "Guest",
    "Pale King",
    "Colorless Queen",
    "Heart Queen",
    "Red King",
    "Jabberwock"
]

ENCOUNTER_INTERIOR = {
    1: "Sleeper",
    6: "Footmen in Livery",
    8: "Cheshire Cat",
    11: "Mome Rath",
    12: "Wolf or Tiger",
    15: "The Rabbit",
    18: "March Hare",
    21: "Pseudoturtle",
    26: "Colorless Pawn",
    31: "Pale Pawn",
    36: "Red Pawn",
    39: "Rose Nageire",
    42: "Tiger Lily Nageire",
    45: "Violet Nageire",
    48: "Order of Spades",
    51: "Order of Hearts",
    54: "Order of Diamonds",
    57: "Order of Clubs",
    58: "Pudding",
    61: "Colorless Knight",
    64: "Pale Knight",
    67: "Red Knight",
    69: "Colorless Bishop",
    71: "Pale Bishop",
    73: "Red Bishop",
    75: "Duchess",
    77: "Knave of Hearts",
    79: "Hatter",
    80: "Pale Rook",
    83: "Colorless Rook",
    85: "Red Rook",
    86: "Sphinx",
    88: "Red Bride (Ilona)",
    90: "Red Bride (Tizala)",
    92: "Red Bride (Ildana)",
    93: "King of Hearts",
    96: "Guest",
    97: "Pale King",
    98: "Colorless Queen",
    99: "Heart Queen",
    100: "Red King"
}

ENCOUNTER_GARDEN_NIGHT = {
    3: "Bat/Undead bird Swarm",
    5: "Little Crocodile",
    6: "Ozwick",
    8: "Sleeper",
    11: "Footmen in Livery",
    13: "Cheshire Cat",
    14: "Mome Rath",
    16: "The Rabbit",
    18: "March Hare",
    20: "Tove",
    22: "Pseudoturtle",
    27: "Colorless Pawn",
    32: "Pale Pawn",
    37: "Red Pawn",
    40: "Rose Nageire",
    43: "Tiger Lily Nageire",
    46: "Violet Nageire",
    50: "Order of Spades",
    53: "Order of Hearts",
    56: "Order of Diamonds",
    59: "Order of Clubs",
    61: "Jub",
    62: "Unicorn",
    65: "Colorless Knight",
    68: "Pale Knight",
    71: "Red Knight",
    73: "Colorless Bishop",
    75: "Pale Bishop",
    77: "Red Bishop",
    79: "Duchess",
    81: "Knave of Hearts",
    83: "Hatter",
    85: "Pale Rook",
    87: "Colorless Rook",
    89: "Red Rook",
    90: "Sphinx",
    91: "Red Bride (Ilona)",
    92: "Red Bride (Tizala)",
    93: "Red Bride (Ildana)",
    94: "King of Hearts",
    96: "Guest",
    97: "Pale King",
    98: "Colorless Queen",
    99: "Heart Queen",
    100: "Red King"
}

ENCOUNTER_GARDEN_DAY = {
    5: "Little Crocodile",
    6: "Ozwick",
    8: "Sleeper",
    15: "Footmen in Livery",
    18: "Cheshire Cat",
    24: "Mome Rath",
    25: "Wolf or Tiger",
    29: "The Rabbit",
    33: "March Hare",
    40: "Tove",
    43: "Pseudoturtle",
    50: "Rose Nageire",
    56: "Tiger Lily Nageire",
    63: "Violet Nageire",
    70: "Jub",
    71: "Unicorn",
    74: "Duchess",
    78: "Hatter",
    84: "Pale Rook",
    90: "Colorless Rook",
    95: "Red Rook",
    97: "Sphinx",
    100: "Guest"
}

ENCOUNTER_FOREST_NIGHT = {
    3: "Bat/Undead bird Swarm",
    4: "Little Crocodile",
    5: "Ozwick",
    6: "Sleeper",
    7: "Ordinary Human",
    9: "Goblins, Hobgoblins, etc.",
    11: "Footmen in Livery",
    13: "Cheshire Cat",
    15: "Mome Rath",
    17: "Wild Boar",
    19: "Wolf or Tiger",
    21: "The Rabbit",
    23: "March Hare",
    25: "Tove",
    27: "Pseudoturtle",
    29: "Colorless Pawn",
    31: "Pale Pawn",
    33: "Red Pawn",
    35: "Order of Spades",
    37: "Order of Hearts",
    39: "Order of Diamonds",
    42: "Order of Clubs",
    46: "Jub",
    48: "Pudding",
    49: "Unicorn",
    53: "Witch (any old witch)",
    56: "Colorless Knight",
    59: "Pale Knight",
    62: "Red Knight",
    66: "Great Grey Grub",
    68: "Colorless Bishop",
    70: "Pale Bishop",
    72: "Red Bishop",
    74: "Duchess",
    76: "Knave of Hearts",
    78: "Hatter",
    81: "Pale Rook",
    84: "Colorless Rook",
    87: "Red Rook",
    88: "Sphinx",
    89: "Red Bride (Ilona)",
    90: "Red Bride (Tizala)",
    91: "Red Bride (Ildana)",
    92: "King of Hearts",
    95: "Guest",
    96: "Pale King",
    97: "Colorless Queen",
    98: "Heart Queen",
    99: "Red King",
    100: "Jabberwock"
}

ENCOUNTER_FOREST_DAY = {
    2: "Little Crocodile",
    3: "Ozwick",
    4: "Sleeper",
    8: "Ordinary Human",
    13: "Goblins, Hobgoblins, etc.",
    18: "Footmen in Livery",
    21: "Cheshire Cat",
    25: "Mome Rath",
    29: "Wild Boar",
    37: "Wolf or Tiger",
    40: "The Rabbit",
    43: "March Hare",
    50: "Tove",
    54: "Pseudoturtle",
    61: "Jub",
    65: "Pudding",
    66: "Unicorn",
    71: "Witch (any old witch)",
    76: "Great Grey Grub",
    80: "Duchess",
    84: "Hatter",
    88: "Pale Rook",
    92: "Colorless Rook",
    96: "Red Rook",
    97: "Sphinx",
    99: "Guest",
    100: "Jabberwock"
}

ENCOUNTER_HOUSE_OF_HEARTS = {
    25: "Footmen in Livery",
    28: "Cheshire Cat",
    29: "Wolf or Tiger",
    32: "The Rabbit",
    35: "Pseudoturtle",
    50: "Order of Spades",
    64: "Order of Hearts",
    79: "Order of Diamonds",
    93: "Order of Clubs",
    96: "Duchess",
    98: "Knave of Hearts",
    99: "King of Hearts",
    100: "Heart Queen"
}

ENCOUNTER_PALE_HOUSE = {
    "Bat/Undead bird Swarm",
    "Little Crocodile",
    "Ozwick",
    "Sleeper",
    "Ordinary Human",
    "Goblins, Hobgoblins, etc.",
    "Footmen in Livery",
    "Cheshire Cat",
    "Mome Rath",
    "Wild Boar",
    "Wolf or Tiger",
    "The Rabbit",
    "March Hare",
    "Tove",
    "Pseudoturtle",
    "Colorless Pawn",
    "Pale Pawn",
    "Red Pawn",
    "Rose Nageire",
    "Tiger Lily Nageire",
    "Violet Nageire",
    "Order of Spades",
    "Order of Hearts",
    "Order of Diamonds",
    "Order of Clubs",
    "Jub",
    "Pudding",
    "Unicorn",
    "Witch (any old witch)",
    "Colorless Knight",
    "Pale Knight",
    "Red Knight",
    "Great Grey Grub",
    "Colorless Bishop",
    "Pale Bishop",
    "Red Bishop",
    "Duchess",
    "Knave of Hearts",
    "Hatter",
    "Pale Rook",
    "Colorless Rook",
    "Red Rook",
    "Sphinx",
    "Red Bride (Ilona)",
    "Red Bride (Tizala)",
    "Red Bride (Ildana)",
    "King of Hearts",
    "Guest",
    "Pale King",
    "Colorless Queen",
    "Heart Queen",
    "Red King",
    "Jabberwock"
}

ENCOUNTER_RED_HOUSE = {
    "Bat/Undead bird Swarm",
    "Little Crocodile",
    "Ozwick",
    "Sleeper",
    "Ordinary Human",
    "Goblins, Hobgoblins, etc.",
    "Footmen in Livery",
    "Cheshire Cat",
    "Mome Rath",
    "Wild Boar",
    "Wolf or Tiger",
    "The Rabbit",
    "March Hare",
    "Tove",
    "Pseudoturtle",
    "Colorless Pawn",
    "Pale Pawn",
    "Red Pawn",
    "Rose Nageire",
    "Tiger Lily Nageire",
    "Violet Nageire",
    "Order of Spades",
    "Order of Hearts",
    "Order of Diamonds",
    "Order of Clubs",
    "Jub",
    "Pudding",
    "Unicorn",
    "Witch (any old witch)",
    "Colorless Knight",
    "Pale Knight",
    "Red Knight",
    "Great Grey Grub",
    "Colorless Bishop",
    "Pale Bishop",
    "Red Bishop",
    "Duchess",
    "Knave of Hearts",
    "Hatter",
    "Pale Rook",
    "Colorless Rook",
    "Red Rook",
    "Sphinx",
    "Red Bride (Ilona)",
    "Red Bride (Tizala)",
    "Red Bride (Ildana)",
    "King of Hearts",
    "Guest",
    "Pale King",
    "Colorless Queen",
    "Heart Queen",
    "Red King",
    "Jabberwock"
}

ENCOUNTER_COLORLESS_HOUSE = {
    "Bat/Undead bird Swarm",
    "Little Crocodile",
    "Ozwick",
    "Sleeper",
    "Ordinary Human",
    "Goblins, Hobgoblins, etc.",
    "Footmen in Livery",
    "Cheshire Cat",
    "Mome Rath",
    "Wild Boar",
    "Wolf or Tiger",
    "The Rabbit",
    "March Hare",
    "Tove",
    "Pseudoturtle",
    "Colorless Pawn",
    "Pale Pawn",
    "Red Pawn",
    "Rose Nageire",
    "Tiger Lily Nageire",
    "Violet Nageire",
    "Order of Spades",
    "Order of Hearts",
    "Order of Diamonds",
    "Order of Clubs",
    "Jub",
    "Pudding",
    "Unicorn",
    "Witch (any old witch)",
    "Colorless Knight",
    "Pale Knight",
    "Red Knight",
    "Great Grey Grub",
    "Colorless Bishop",
    "Pale Bishop",
    "Red Bishop",
    "Duchess",
    "Knave of Hearts",
    "Hatter",
    "Pale Rook",
    "Colorless Rook",
    "Red Rook",
    "Sphinx",
    "Red Bride (Ilona)",
    "Red Bride (Tizala)",
    "Red Bride (Ildana)",
    "King of Hearts",
    "Guest",
    "Pale King",
    "Colorless Queen",
    "Heart Queen",
    "Red King",
    "Jabberwock"
}

ENCOUNTER_INTELLIGENT = {
    "Bat/Undead bird Swarm",
    "Little Crocodile",
    "Ozwick",
    "Sleeper",
    "Ordinary Human",
    "Goblins, Hobgoblins, etc.",
    "Footmen in Livery",
    "Cheshire Cat",
    "Mome Rath",
    "Wild Boar",
    "Wolf or Tiger",
    "The Rabbit",
    "March Hare",
    "Tove",
    "Pseudoturtle",
    "Colorless Pawn",
    "Pale Pawn",
    "Red Pawn",
    "Rose Nageire",
    "Tiger Lily Nageire",
    "Violet Nageire",
    "Order of Spades",
    "Order of Hearts",
    "Order of Diamonds",
    "Order of Clubs",
    "Jub",
    "Pudding",
    "Unicorn",
    "Witch (any old witch)",
    "Colorless Knight",
    "Pale Knight",
    "Red Knight",
    "Great Grey Grub",
    "Colorless Bishop",
    "Pale Bishop",
    "Red Bishop",
    "Duchess",
    "Knave of Hearts",
    "Hatter",
    "Pale Rook",
    "Colorless Rook",
    "Red Rook",
    "Sphinx",
    "Red Bride (Ilona)",
    "Red Bride (Tizala)",
    "Red Bride (Ildana)",
    "King of Hearts",
    "Guest",
    "Pale King",
    "Colorless Queen",
    "Heart Queen",
    "Red King",
    "Jabberwock"
}

EVENT = {}

FOREST_LANDMARK = []

GARDEN_LANDMARK = []

INTERIOR_ROOM = []

COMPLICATION = []

LOCATION = {}

OBJECT = []

PERPLEXITY_COMMON = []

PERPLEXITY_UNCOMMON = []

NPC_RELATIONSHIP = {}

DOING_RELATIONSHIP = []

DOING_WANT = []

DOING_CARE = []
